apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: johnsvanda/auth
          resources:
            requests:
              memory: "1Gi"  # Adjusted from 4Gi to 1Gi
              cpu: "500m"    # Adjusted as needed
            limits:
              memory: "2Gi"  # Adjusted as needed
              cpu: "1000m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000